environment:
  matrix:
    - compiler: msys2
      ARCH: x64
      MSYS2_ARCH: x86_64
      MSYS2_DIR: msys64
      MSYSTEM: MINGW64
    - compiler: msys2
      ARCH: x86
      MSYS2_ARCH: i686
      MSYS2_DIR: msys64
      MSYSTEM: MINGW32

# matrix:
#   allow_failures:
#     # - platform: x64
#     #   nodejs_version: "0.10"
#     # - platform: x86
#     #   nodejs_version: "0.10"
#     # - platform: x64
#     #   nodejs_version: "4.0"
#     # - platform: x86
#     #   nodejs_version: "4.0"
#     # - platform: x64
#     #   nodejs_version: "5.0"
#     # - platform: x86
#     #   nodejs_version: "5.0"
init:
  - git config --global core.autocrlf true
install:
  - git clone https://github.com/gnucash/gnucash-on-windows c:\gnucash-on-windows
  - ps: c:\gnucash-on-windows\setup-mingw.ps1

build_script:
  - '%APPVEYOR_BUILD_FOLDER%\appveyor.bat build'

# test_script:
#   # Output useful info for debugging.
#   - node --version
#   - npm --version
#   - dir c:\projects\node-canvas-builder\package\binlib
#   # run tests
#   - cd c:\projects\node-canvas-builder\package\test
#   - node test.js
#   #- ps: 7z a c:\projects\node-canvas-builder\packed\win_$env:platform`_$env:nodejs_version.zip c:\projects\node-canvas-builder\package\*
#   - cd c:\projects\node-canvas-builder\packed
#   - npm pack c:\projects\node-canvas-builder\package
#   - ps: Rename-Item c:\projects\node-canvas-builder\packed\canvas-bin-1.3.7.tgz win_$env:platform`_$env:nodejs_version.tar.gz
#   - dir c:\projects\node-canvas-builder\packed
# artifacts:
#   # - path: node-canvas-builder\win_$(platform)_$(env:node_version).zip
#   - path: packed\*.tar.gz
#     name: package
#   #   name: win
  #   name: win$(env:PLATFORM)_$(env:nodejs_version)
  #   type: zip
# deploy:
#   provider: GitHub
#   #artifact: win_$(platform)_$(Env:nodejs_version).zip
#   artifact: package
#   auth_token:
#     secure: VOpd1LzyZp339s73kSoR47YMHImz8uN8cGCB/9tBnXBjmh8TlC1mMqTgUdAlCKPI
#   on:
#     branch: master
#     appveyor_repo_tag: true        # deploy on tag push only
